FROM registry.access.redhat.com/ubi9/python-311:latest

WORKDIR /mcpserver

COPY requirements.txt /mcpserver/
RUN pip install -r requirements.txt

RUN pip install mcp["cli"]

COPY . /mcpserver

EXPOSE 8000

ENTRYPOINT ["python", "local-mcp-server.py"]
